import React,{useState, useEffect, useRef} from 'react'
import type { NextPage } from 'next'
import { useRouter } from 'next/router'
import Link from 'next/link'
import Head from 'next/head'
import * as THREE from "three"

import FollowCursor from './components/FollowerCursor'
import Landing from './components/Landing'
import { motion } from "framer-motion";
import TweenLite ,{gsap} from 'gsap'
import {CustomEase} from "gsap/CustomEase";
gsap.registerPlugin(CustomEase);
const color1 = '#000'
const color2 = '#e2e2e2'

const Home: NextPage = () => {

  const router = useRouter()

  const [isDark, setDark] = useState(true)
  const swiperImages = useRef<HTMLHeadingElement>(null);
  const footer = useRef<HTMLHeadingElement>(null)
  const closebtn = useRef<HTMLHeadingElement>(null)
  let mouse = new THREE.Vector2() 

  const changeDarkTheme = (value:boolean) => {
    localStorage.setItem('dark', value?'1':'0')
    setDark(value)
  }
  
  function AnimationText(){

    CustomEase.create("cubic-bezier", ".19,1,.22,1")
    gsap.to(swiperImages.current, 1, { y:0, opacity:1, ease: 'cubic-bezier', delay:3.1});
    
    let animations = document.getElementsByClassName('mobile-menu-text-animation')
    if (animations.length > 0) {
      for (let i = 0; i < animations.length; i++) {
        let animation = animations[i]
        gsap.to(animation, 1, { top: 0, ease: 'cubic-bezier', delay: (2.5 + (i / 4)) });
      }
    }
    
    let contactanimations = document.getElementsByClassName('mobile-menu-contact-animation')
    if (contactanimations.length > 0) {
      for (let i = 0; i < contactanimations.length; i++) {
        let animation = contactanimations[i]
        gsap.to(animation, 1, { top: 0, ease: 'cubic-bezier', delay: (2.5 + (i / 4)) });
      }
    }
    
    if (footer.current){      
      if (footer.current.children.length > 0) {
        for (let i = 0; i < footer.current.children.length; i++) {
          let animation = footer.current.children[i]
          gsap.to(animation, 1, {opacity: 1, y: 0, ease: 'cubic-bezier', delay: (3.5 + (i / 4)) });
        }
      }
    }
    
    if (closebtn.current){      
      if (closebtn.current.children.length > 0) {
        for (let i = 0; i < closebtn.current.children.length; i++) {
          let animation = closebtn.current.children[i]
          gsap.to(animation, 1, {opacity: 1, y: 0, ease: 'cubic-bezier', delay: (3.5 + (i / 4)) });
        }
      }
    }
  }

  useEffect(() => {    
    if(typeof window !== "undefined"){
      AnimationText();
    }

    var studioDark = localStorage.getItem('dark')
    if(studioDark===null){
      localStorage.setItem('dark','1')
    }else{
      setDark(studioDark==='1')
    }
  }, [])

  const buttonOverIn = () =>{
    let cursor = document.getElementById('cursor')
    gsap.to(cursor, { scale:3, opacity:0.3});
  }

  const buttonOverOut = () =>{    
    let cursor = document.getElementById('cursor')
    gsap.to(cursor, { scale:1, opacity:1});    
  }

  const animation = {
    exit : {
      y: 250,
      transition: {
        duration: 1,
        ease: [.19,1,.22,1]
      }
    },
    exitTwo : {
      y: 250,
      opacity:0,
      transition: {
        duration: 1,
        ease: [.19,1,.22,1]
      }
    },
    exit3 : {
      y: 250,
      opacity:0,
      transition: {
        duration: 1,
        ease: [.19,1,.22,1]
      }
    },
  }
  return (
    <>
      <Head>
        <title>Studio/Menu</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Landing/>
      
      <div className="w-full fixed" style={{background:isDark?color1:color2, color:isDark?color2:color1}}>
        <div className='max-w-[390px] pt-10 px-6 mx-auto uppercase min-h-[100vh] max-h-[844px] overflow-hidden'>
          <motion.div exit='exit' className="content">
            
            <div className='relative w-full h-[25px] overflow-hidden'>
              <motion.p variants={animation} className="mobile-menu-text-animation text-20 font-bold absolute top-[100px] left-0">STUDIO©</motion.p>
            </div>
            
            <motion.div className='mt-[40px] text-[50px]'>
              <div className='relative w-full h-[77px] overflow-hidden' style={{borderBottom:`1px solid ${isDark?color2:color1}`}}>
                <motion.p variants={animation} className="mobile-menu-text-animation font-normal absolute top-[100px] left-0">
                  <div className='flex items-start'>
                    <div className='text-[15px] mr-5 mt-4'>01</div>
                    <Link href={'/service'}><a>Sevices</a></Link>
                  </div>
                </motion.p>
              </div>
              <div className='relative w-full h-[77px] overflow-hidden' style={{borderBottom:`1px solid ${isDark?color2:color1}`}}>
                <motion.p variants={animation} className="mobile-menu-text-animation font-normal absolute top-[100px] left-0">
                  <div className='flex items-start'>
                    <div className='text-[15px] mr-5 mt-4'>02</div>
                    <Link href={'#'}><a>work</a></Link>                    
                  </div>
                </motion.p>
              </div>
              <div className='relative w-full h-[77px] overflow-hidden' style={{borderBottom:`1px solid ${isDark?color2:color1}`}}>
                <motion.p variants={animation} className="mobile-menu-text-animation font-normal absolute top-[100px] left-0">
                  <div className='flex items-start'>
                    <div className='text-[15px] mr-5 mt-4'>03</div>
                    <Link href={'/about'}><a>about</a></Link> 
                  </div>
                </motion.p>
              </div>
              <div className='relative w-full h-[77px] overflow-hidden'>
                <motion.p variants={animation} className="mobile-menu-text-animation font-normal absolute top-[100px] left-0">
                  <div className='flex items-start'>
                    <div className='text-[15px] mr-5 mt-4'>04</div>
                    <Link href={'/contact'}><a>contact</a></Link> 
                  </div>
                </motion.p>
              </div>
            </motion.div>
            
            <div  className='w-16 mx-auto my-[60px]'>              
              <motion.section variants={animation} exit="exit3" ref={closebtn}>
                <div style={{opacity:0, transform:"translate(0,200px)"}} onClick={() => router.back()}>
                  <svg width="64" height="66" viewBox="0 0 64 66" fill="none" xmlns="http://www.w3.org/2000/svg">
                    <line x1="62.7071" y1="2.70711" x2="0.707106" y2="64.7071" stroke={isDark?'white':'black'} strokeWidth="2"/>
                    <line x1="0.707107" y1="1.29289" x2="62.7071" y2="63.2929" stroke={isDark?'white':'black'} strokeWidth="2"/>
                  </svg>                 
                </div>                
              </motion.section>
            </div>
            
            <motion.div>
              <div className='mt-[46px] mb-10 text-[16px] flex'>
                <div className='w-[220px]'>
                  <div className='relative h-[20px] overflow-hidden'>
                    <motion.p variants={animation} className="mobile-menu-contact-animation font-normal absolute top-[100px] left-0">
                      Behance
                    </motion.p>
                  </div>
                  <div className='relative h-[20px] overflow-hidden'>
                    <motion.p variants={animation} className="mobile-menu-contact-animation font-normal absolute top-[100px] left-0">
                      Facebook
                    </motion.p>
                  </div>
                  <div className='relative h-[20px] overflow-hidden'>
                    <motion.p variants={animation} className="mobile-menu-contact-animation font-normal absolute top-[100px] left-0">
                      Instagram
                    </motion.p>
                  </div>
                  <div className='relative h-[20px] overflow-hidden'>
                    <motion.p variants={animation} className="mobile-menu-contact-animation font-normal absolute top-[100px] left-0">
                      Linkedin
                    </motion.p>
                  </div>
                </div>
                
                <div className='w-full'>
                  <div className='relative h-[20px] overflow-hidden'>
                    <motion.p variants={animation} className="mobile-menu-contact-animation font-normal absolute top-[100px] left-0">
                      (213) 533-8208
                    </motion.p>
                  </div>
                  <div className='relative h-[20px] overflow-hidden'>
                    <motion.p variants={animation} className="mobile-menu-contact-animation font-normal absolute top-[100px] left-0 underline">
                      studio@sTUDIO.co
                    </motion.p>
                  </div>
                </div>
              </div>
            </motion.div>

            <section id='footer'>
              <motion.section variants={animation} exit="exitTwo" ref={footer}>
                <div style={{opacity:0, transform:"translate(0,200px)"}}>
                  <div className='text-white flex items-center relative mx-4 md:ml-16'>
                    <img src='img/maskLeft.png' style={{height:'100%', display:isDark?'block':'none'}} className="absolute top-0 left-[0px] z-10 pointer-events-none"/>
                    <img src='img/maskleftlight.png' style={{height:'100%', display:isDark?'none':'block'}} className="absolute top-0 left-[0px] z-10 pointer-events-none"/>
                    <button className={isDark?"animation-button mx-[1px]":"animation-button blue-button mx-[1px]"} onClick={() => changeDarkTheme(!isDark)}
                      style={{border:isDark?'solid 3px #FF5C00':'solid 3px #0019FF'}} onMouseMove={buttonOverIn} onMouseLeave={buttonOverOut}
                    >
                      <div className='btn-content' style={{height:'56px !important', color:isDark?'white':'black'}}>
                        <div className='btn-content-group mx-4 text-[32px]'>
                          SDA / LA
                        </div>
                      </div>            
                    </button>
                    <img src='img/maskRight.png' style={{height:'100%', display:isDark?'block':'none'}} className="absolute top-0 right-[0px] z-10 pointer-events-none"/>
                    <img src='img/maskrightlight.png' style={{height:'100%', display:isDark?'none':'block'}} className="absolute top-0 right-[0px] z-10 pointer-events-none"/>
                  </div>                  
                </div>
                <p style={{opacity:0, transform:"translate(0,200px)"}} className="text-16 text-center mt-4 pb-8">2022© STUDIO LLC. All Rights Reserved.</p>  
              </motion.section>
            </section>
            
          </motion.div>
        </div>
      </div>

      <div className="hidden md:block"><FollowCursor/></div>      
    </>
  )
}
export default Home